### PR TITLE
PHP7 support

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by archwisp** [comment]
Thanks for the PR! Unfortunately, the build is now failing because coverallis seems to require 5.5+ but the library supports 5.3+. If you can find a way to get the build to pass with 5.3+ (probably pin the coverallis version), I can merge the request.

**Comment by umpirsky** [comment]
@archwisp We should use `"satooshi/php-coveralls": "~1.0"` since it supports PHP 5.3, not `dev-master`. Any reason to use `dev-master`?

I tried to use `"satooshi/php-coveralls": "~1.0"`, but I got:

```
$ composer update satooshi/php-coveralls
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/yaml (v2.8.2)
    Downloading: 100%         

  - Installing symfony/stopwatch (v3.0.1)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.0.1)
    Loading from cache

  - Installing symfony/console (v3.0.1)
    Loading from cache

  - Installing symfony/filesystem (v3.0.1)
    Loading from cache

  - Installing symfony/config (v3.0.1)
    Downloading: 100%         

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.8.2)
    Downloading: 100%         

  - Installing guzzle/guzzle (v3.9.3)
    Loading from cache

  - Installing satooshi/php-coveralls (v1.0.0)
    Downloading: 100%         

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (1.2.3)
    Loading from cache

  - Installing phpunit/php-timer (1.0.7)
    Loading from cache

  - Installing phpunit/php-token-stream (1.2.2)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.4.1)
    Loading from cache

  - Installing phpunit/php-code-coverage (1.2.18)
    Downloading: 100%         

  - Installing phpunit/phpunit (3.7.38)
    Downloading: 100%         

symfony/console suggests installing symfony/process ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
satooshi/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
Warning: Ambiguous class resolution, "PHPCS_Sniffs_ControlStructures_ControlSignatureSniff" was found in both "vendor/phpunit/phpunit/build/PHPCS/Sniffs/ControlStructures/ControlSignatureSniff.php" and "vendor/phpunit/php-token-stream/build/PHPCS/Sniffs/ControlStructures/ControlSignatureSniff.php", the first will be used.
Warning: Ambiguous class resolution, "PHPCS_Sniffs_Whitespace_ConcatenationSpacingSniff" was found in both "vendor/phpunit/phpunit/build/PHPCS/Sniffs/Whitespace/ConcatenationSpacingSniff.php" and "vendor/phpunit/php-token-stream/build/PHPCS/Sniffs/Whitespace/ConcatenationSpacingSniff.php", the first will be used.
Warning: Ambiguous class resolution, "PHPCS_Sniffs_ControlStructures_ControlSignatureSniff" was found in both "vendor/phpunit/phpunit/build/PHPCS/Sniffs/ControlStructures/ControlSignatureSniff.php" and "vendor/phpunit/php-code-coverage/build/PHPCS/Sniffs/ControlStructures/ControlSignatureSniff.php", the first will be used.
Warning: Ambiguous class resolution, "PHPCS_Sniffs_Whitespace_ConcatenationSpacingSniff" was found in both "vendor/phpunit/phpunit/build/PHPCS/Sniffs/Whitespace/ConcatenationSpacingSniff.php" and "vendor/phpunit/php-code-coverage/build/PHPCS/Sniffs/Whitespace/ConcatenationSpacingSniff.php", the first will be used.
Warning: Ambiguous class resolution, "PHPCS_Sniffs_ControlStructures_ControlSignatureSniff" was found in both "vendor/phpunit/phpunit/build/PHPCS/Sniffs/ControlStructures/ControlSignatureSniff.php" and "vendor/phpunit/phpunit-mock-objects/build/PHPCS/Sniffs/ControlStructures/ControlSignatureSniff.php", the first will be used.
Warning: Ambiguous class resolution, "PHPCS_Sniffs_Whitespace_ConcatenationSpacingSniff" was found in both "vendor/phpunit/phpunit/build/PHPCS/Sniffs/Whitespace/ConcatenationSpacingSniff.php" and "vendor/phpunit/phpunit-mock-objects/build/PHPCS/Sniffs/Whitespace/ConcatenationSpacingSniff.php", the first will be used.
```

Why do we need ["classmap": [""],](https://github.com/archwisp/PHPEncryptData/blob/master/composer.json#L12)?

**Comment by johnkary** [comment]
@umpirsky Thanks for the PR! I opened the following PRs to fix the issues you found:

#19 - Remove classmap from Composer config
#20 - Pin satooshi/php-coveralls to PHP 5.3+ compatible version

Once those are merged we can rebase against master to see your PR's updated Travis runs.

**Comment by umpirsky** [comment]
@johnkary Wow, that was fast! :trollface: 

However, better ever then never. :)

**Pull request merged**
